### ISSUE TITLE
no headers added to response

### ISSUE THREAD

**Issue by vientorepublic** [awesometic/nestjs-request-id#13]
NestJS Version: 10.0.0

After applying the module to AppModule:
<img width="423" alt="스크린샷 2023-11-30 오전 8 29 04" src="https://github.com/awesometic/nestjs-request-id/assets/107330816/df937d66-84c9-4a14-9e96-2bca2967da07">

Try adding X-Request-Id header in middleware:
<img width="733" alt="스크린샷 2023-11-30 오전 8 30 24" src="https://github.com/awesometic/nestjs-request-id/assets/107330816/7f078440-d8b1-4a57-be3c-026cd3db7b3d">
<img width="735" alt="스크린샷 2023-11-30 오전 8 33 36" src="https://github.com/awesometic/nestjs-request-id/assets/107330816/a712058f-ba76-4f95-8514-43847985fd3f">

**Comment by awesometic** [comment]
Hello,

How did you apply this module to the AppModule? Can you paste the code block here partly?

**Comment by vientorepublic** [comment]
I applied it to the imports of the module decorator as follows:
```js
import { LoggerMiddleware } from './middleware/logger.middleware';
import { RequestIdFormatType, RequestIdModule } from 'nestjs-request-id';

@Module({
  imports: [
    RequestIdModule.register({
      type: RequestIdFormatType.UUID_V4,
    }),
    // other modules...
  ],
  controllers: [],
  providers: [],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(LoggerMiddleware).forRoutes('*');
  }
}
```

**Comment by awesometic** [comment]
Thanks,

If I understand right, you can trace the request in the NestJS life cycle but can't see that identifier in the received response.
I will patch that to add the same header to the response soon.

Thanks for the feedback :)

**Comment by vientorepublic** [comment]
Is it possible to set a header using `setHeader` among the `response` parameter methods in requestid.middleware.ts?

**Comment by awesometic** [comment]
Maybe yes, you can try it on your side and share the results :)
